---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springyboing/docker-gradlew

run:
  path: pcf-pipelines/tasks/mongo-broker/build.sh

inputs:
- name: pcf-pipelines 
- name: broker-repo
outputs:
- name: binary
